USE [master]
GO

/****** Object:  Database [DoctorApp]    Script Date: 3.2.2024. 13:38:27 ******/
CREATE DATABASE [DoctorApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DoctorApp', FILENAME = N'C:\DoctorAppBackup\DoctorApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DoctorApp_log', FILENAME = N'C:\DoctorAppBackup\DoctorApp.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DoctorApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DoctorApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DoctorApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DoctorApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DoctorApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DoctorApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [DoctorApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DoctorApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DoctorApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DoctorApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DoctorApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DoctorApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DoctorApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DoctorApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DoctorApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DoctorApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DoctorApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DoctorApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DoctorApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DoctorApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DoctorApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DoctorApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DoctorApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DoctorApp] SET RECOVERY FULL 
GO

ALTER DATABASE [DoctorApp] SET  MULTI_USER 
GO

ALTER DATABASE [DoctorApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DoctorApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DoctorApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DoctorApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DoctorApp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DoctorApp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DoctorApp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DoctorApp] SET  READ_WRITE 
GO

